[general]
import = ["~/.config/alacritty/themes/default.toml"]

# Font configuration (changes require restart)
[font]
normal.family = "Inconsolata"
size = 18

[window.dimensions]
columns = 80
lines = 24

[scrolling]
history = 0
